### ISSUE TITLE
Box or Seal

### ISSUE THREAD

**Issue by adamcaudill** [adamcaudill/SmartEncryption#8]
Should we use `crypto_box`, or `crypto_box_seal` - if we use seal, then the "sender" can't go back an decrypt it later, which is likely what they expect. But this also breaks any authentication, as you can't know who sent it.

Options:

* Use box, and document that either party can decrypt.
* Use seal, and document that it isn't authenticated.
* Use box with an ephemeral key pair, signing the ephemeral public key with the sender's private key. This would be the best of both, but more complex.

Thoughts?

**Comment by paragonie-scott** [comment]
This might sound clunky or counterintuitive, but what about a two-step process:

1. `crypto_sign()` the plaintext message with a long-term identity key
2. `crypto_box_seal()` the signed message (and, maybe, their long-term identity public key?)

(Note: Signing with EdDSA then encrypting the signed message is different than MAC-then-Encrypt. IIRC `crypto_box_seal()` still uses authenticated encryption to prevent tampering.)

**Comment by adamcaudill** [comment]
Perhaps add an `Identity.GenerateIdentity()` method that returns an `Identity` object (basically a wrapper for [Sodium.KeyPair](https://github.com/adamcaudill/libsodium-net/blob/master/libsodium-net/KeyPair.cs), with an Ed25519 key pair) - that would give a clear way to generate the long term idenity key. That key could be used to either perform the sign of the plaintext, or the ephemeral public key.

I'm thinking something like this (ephemeral public key, signature on the public key):

    version[1] || identity_public_key[32] || ephemeral_public_key[32] || 
      signature[64] || nonce[24] || data[length - 153]

This should confirm that the identity of the sender, without allowing them to decrypt it, though does make the header rather large. The recipient can then chose whether or not to verify the identity of the sender.

**Comment by CodesInChaos** [comment]
You might want to take a look at [noise boxes](https://github.com/trevp/noise/wiki/Boxes).
